/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as libraries from "./libraries";
export type { libraries };
export type { AutomationBase } from "./AutomationBase";
export type { ConfirmedOwner } from "./ConfirmedOwner";
export type { ConfirmedOwnerWithProposal } from "./ConfirmedOwnerWithProposal";
