/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AutomationCompatibleInterface } from "./AutomationCompatibleInterface";
export type { OwnableInterface } from "./OwnableInterface";
